services:
  - type: web
    name: piper-tts-demo
    env: docker
    plan: free
    healthCheckPath: /healthz
    envVars:
      - key: TTS_API_KEY
        sync: false        # ustawisz w Render Dashboard (tajny klucz)
      - key: ALLOWED_ORIGINS
        value: https://joamas.pl   
      - key: PIPER_MODEL
        value: pl_PL-gosia-medium.onnx
